baseURL = "https://prashantv.com/"
title = "@prashantv"
paginate = 5
theme = "PaperModX"
enableRobotsTXT = true
pygmentsUseClasses = true

# stop tags like #go becoming #Go
# we'll manually manage case in the content
titleCaseStyle = "none"

[params]
env = "production"
title = "@prashantv"
description = "prashantv // about + posts"
keywords = [ "prashantv", "Prashant Varanasi", "posts" ]
DateFormat = "Jan 2 2006"
ShowPostNavLinks = true
ShowCodeCopyButtons = true
showtoc = true

  [params.homeInfoParams]
  Title = "Prashant Varanasi"
  Content = "Software Engineer, SF"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/prashantv"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/prashantv"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/prashantvaranasi/"

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 40

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 70

